byoverbs/bin/: Add 'qco', distinct from 'q'
so as to stop accidental 'q .' from meaning 'qco .' which is to discard all 'qd'

for example

    % q .
    /Users/jqdoe/bin/q: ERROR: unrecognized arguments: .
    %

diff --git a/bin/q b/bin/q
--- a/bin/q
+++ b/bin/q
@@ -1,2 +1,7 @@
+if [[ $# != 0 ]]; then
+    echo "$0: ERROR: unrecognized arguments: $@"
+    exit 2  # exit 2 for wrong args
+fi
+
 set -xe
-git checkout "$@"
+git checkout
